/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d4e3ff",
        "on-surface": "#191c1d",
        "tertiary-fixed": "#ffe16d",
        "on-tertiary-fixed": "#221b00",
        "on-error-container": "#93000a",
        "primary-fixed": "#d5e3ff",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed-dim": "#e9c400",
        "secondary-container": "#b9d3fd",
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#001b3c",
        "on-secondary-fixed-variant": "#2e486b",
        primary: "#001e40",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        background: "#f8f9fa",
        "secondary-fixed-dim": "#aec8f1",
        "primary-container": "#003366",
        "on-primary-container": "#799dd6",
        tertiary: "#705d00",
        "surface-dim": "#d9dadb",
        "on-background": "#191c1d",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#4c3e00",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary": "#ffffff",
        "surface-tint": "#3a5f94",
        "on-secondary-fixed": "#001c39",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e3e4",
        "surface-container-highest": "#e1e3e4",
        error: "#ba1a1a",
        surface: "#f8f9fa",
        "on-secondary-container": "#415b7f",
        "on-tertiary-fixed-variant": "#544600",
        secondary: "#466084",
        "surface-container-low": "#f3f4f5",
        "outline-variant": "#c3c6d1",
        outline: "#737780",
        "on-primary": "#ffffff",
        "tertiary-container": "#c9a900",
        "inverse-primary": "#a7c8ff",
        "primary-fixed-dim": "#a7c8ff",
        "on-surface-variant": "#43474f",
        "on-primary-fixed-variant": "#1f477b",
        "surface-container": "#edeeef",
      },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
